--CREACIÓN TABLA Cliente
CREATE TABLE CLIENT
(
    ID NUMBER NOT NULL,
    NAME VARCHAR (4000) NULL,
    EMAIL VARCHAR2 (20) NULL,
    AGE NUMBER NULL,
    PRIMARY KEY(ID)
);

--CREACIÓN SECUENCIA PARA INCREMENTAR 
--AUTOMATICAMENTE EL VALOR DE LA LLAVE PRIMARIA ID
CREATE SEQUENCE cliente_secuencia  START WITH 1 INCREMENT BY 1;

--CREACIÓN DISPARADOR SOBRE LA TABLA CLIENT
--ESTE EVENTO ES PARA QUE INCREMENTE AUTOMATICAMENTE
--CADA VEZ QUE SE INCREMENTE UN REGISTRO EN LA TABLA
CREATE OR REPLACE TRIGGER  cliente_secuencia
    BEFORE INSERT ON CLIENT FOR EACH ROW
    WHEN(NEW.ID IS NULL)
    BEGIN
        SELECT cliente_secuencia.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;

--CREACIÓN TABLA Mensaje
CREATE TABLE MESSAGE
(
    ID NUMBER NOT NULL,
    MESSAGETEXT VARCHAR2 (4000) NULL
);

--CREACIÓN SECUENCIA PARA INCREMENTAR 
--AUTOMATICAMENTE EL VALOR DE LA LLAVE PRIMARIA ID
CREATE SEQUENCE mensaje_secuencia  START WITH 1 INCREMENT BY 1;

--CREACIÓN DISPARADOR SOBRE LA TABLA MESSAGE
--ESTE EVENTO ES PARA QUE INCREMENTE AUTOMATICAMENTE
--CADA VEZ QUE SE INCREMENTE UN REGISTRO EN LA TABLA
CREATE OR REPLACE TRIGGER  mensaje_secuencia
    BEFORE INSERT ON MESSAGE FOR EACH ROW
    WHEN(NEW.ID IS NULL)
    BEGIN
        SELECT cliente_secuencia.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;

--CONSULTAR TODOS LOS REGISTROS DE LA TABLA CLIENTE
SELECT * FROM CLIENT

--CONSULTAR TODOS LOS REGISTROS DE LA MENSAJE
SELECT * FROM MESSAGE


--INSERTAR UN REGISTRO EN LA TABLA
BEGIN 
    INSERT INTO MESSAGE
    (ID, MESSAGETEXT)
    VALUES(:id,:messagetext);
    :status_code:=201;
END;

--INSERTAR UN REGISTRO EN LA TABLA cliente
BEGIN 
    INSERT INTO CLIENT
    (ID, NAME, EMAIL,AGE)
    VALUES(:id,:name,:email,:age);
    :status_code:=201;
END;

--ACTUALIZAR ALGUN REGISTRO DE UNA TABLA Message
BEGIN
    UPDATE MESSAGE
    SET ID = :id, 
    MESSAGETEXT = :messagetext
    WHERE ID = :id;
    :status_code:= 201;
END;

--ELIMINAR ALGUN REGISTRO DE LA TABLA MENSAJE
BEGIN
    DELETE FROM MESSAGE
    WHERE ID = :id;
    :status_code:=204;
END;

--MESSAGE ID
SELECT * FROM MESSAGE WHERE id = :id

--ACTUALIZAR ALGUN REGISTRO DE UNA TABLA cliente
BEGIN
    UPDATE CLIENT
    SET ID = :id, 
    NAME = :name,
    EMAIL=:email,
    AGE=:age
    WHERE ID = :id;
    :status_code:= 201;
END;

--ELIMINAR ALGUN REGISTRO DE LA TABLA cliente
BEGIN
    DELETE FROM CLIENT
    WHERE ID = :id;
    :status_code:=204;
END;

--CLIENT ID
SELECT * FROM CLIENT WHERE id = :id